/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(repeatableHead.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(04dd0fc1454a0b93bcb07de0ad660fbb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/jfab_oot_blocks/repeatableHead.h>
// pydoc.h is automatically generated in the build directory
#include <repeatableHead_pydoc.h>

void bind_repeatableHead(py::module& m)
{

    using repeatableHead = gr::jfab_oot_blocks::repeatableHead;


    py::class_<repeatableHead,
               gr::block,
               gr::basic_block,
               std::shared_ptr<repeatableHead>>(m, "repeatableHead", D(repeatableHead))

          .def(py::init(&repeatableHead::make),
               py::arg("sizeof_stream_item"),
               py::arg("nitems"),
               D(repeatableHead, make))


          .def("increase", &repeatableHead::increase, py::arg("nitems"))

        ;
}
